on: push

jobs:
  one:
    env:
      foo: bar
      environment: dev
      dev-foo: dev-bar
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          thing: ${{ env[format('{0}-{1}', env.environment, 'foo')] }}
        run: echo "$thing"
