on: push

jobs:
  one:
    env:
      foo: bar
    runs-on: ubuntu-16.04
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          thing: ${{ format('{0}{1}', env.foo, '-test') }}
        run: echo "$thing"
